[package]
disabled = true

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
